# Generated by Django 5.1.4 on 2026-02-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_add_member_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleevent',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='day',
            field=models.IntegerField(default=1, help_text='Day number (1 or 2)'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Whether this event/task has been completed'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='location',
            field=models.CharField(blank=True, default='', help_text="e.g. 'Main Hall' or 'Football Field'", max_length=100),
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('schedule_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='competition.scheduleevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
