# Generated by Django 5.1.4 on 2026-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_alter_scheduleevent_options_scheduleevent_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subevent',
            name='speaker_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subevent',
            name='speaker_contact',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subevent',
            name='speaker_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='subevent',
            name='speaker_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
